"""Step 8 — PR: helpers for branch naming, file collection, and PR body generation."""

from __future__ import annotations

import re
from pathlib import Path

from src.pipeline.jira_client import JiraStory

__all__ = ["make_branch_name", "collect_files", "build_pr_body"]


def make_branch_name(story_id: str, title: str) -> str:
    """Return a git-safe branch name: feature/<story-id>-<slug>."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", title.lower()).strip("-")[:40]
    return f"feature/{story_id.lower()}-{slug}"


def collect_files(
    docs_root: Path, src_root: Path
) -> list[tuple[str, str]]:
    """
    Collect all files to push to GitHub.
    Returns list of (relative_path_str, file_content) tuples.
    """
    collected: list[tuple[str, str]] = []

    for doc in sorted(docs_root.rglob("*.md")):
        collected.append((doc.as_posix(), doc.read_text(encoding="utf-8")))

    for py in sorted(src_root.rglob("*.py")):
        collected.append((py.as_posix(), py.read_text(encoding="utf-8")))

    return collected


def build_pr_body(
    story: JiraStory,
    docs_root: Path,
    files_pushed: list[tuple[str, str]],
) -> str:
    """Construct the full GitHub PR description using the pr-writer skill format."""
    changes_rows = "\n".join(
        f"| `{path}` | Added/Updated | SDLC artefact or implementation |"
        for path, _ in files_pushed[:20]  # cap at 20 rows for readability
    )
    extra = f"... and {len(files_pushed) - 20} more files" if len(files_pushed) > 20 else ""

    return f"""## Summary

This PR implements the user story **{story.id}: {story.title}** through a fully
agentic SDLC pipeline powered by GitHub Copilot. All eight SDLC phases — from
requirements through to verification — were executed by Copilot agents using
structured prompts, skills, and instructions defined in this repository.

## Changes Made

| File | Change Type | Reason |
|------|-------------|--------|
{changes_rows}
{extra}

## SDLC Artefacts

- [requirements.md](docs/requirements.md) — Functional & non-functional requirements
- [architecture.md](docs/architecture.md) — System design and component diagrams
- [design-review.md](docs/design-review.md) — Design review findings and verification report
- [impl-plan.md](docs/impl-plan.md) — Dependency-ordered implementation plan

## Test Evidence

See the **Verification Report** section in [docs/design-review.md](docs/design-review.md)
for the full pytest output and coverage percentage.

## Known Limitations

- JIRA ADF parsing falls back to raw text for complex nested blocks.
- Non-Python source files (JS, TS, Java) are not scanned by DocGenerator.
- Pipeline timeout is delegated to CI job configuration (not enforced internally).

## Reviewer Checklist

- [ ] Requirements satisfied (see `docs/requirements.md`)
- [ ] Architecture followed (see `docs/architecture.md`)
- [ ] Design review findings addressed (see `docs/design-review.md`)
- [ ] All tests passing (see Verification Report)
- [ ] No secrets in diff (`git log --diff-filter=A -p | grep -i 'secret\\|password\\|token'`)
- [ ] CHANGELOG updated
- [ ] Docs updated

---
*This PR was generated by the Agentic SDLC Pipeline — GitHub Copilot Capstone Project.*
"""
